site_name: MyNewt

pages:
- Home: index.md
- Geting started:
    - Introduction: 'chapter1/intro.md'
    - Newt Concepts: 'chapter1/newt_concepts.md'
    - First Project: 'chapter1/project1.md'
     
theme: mkdocs 

