site_name: MyNewt

pages:
- 'Introduction': intro.md
- 'Tutorial #1': 
    - 'Environment Setup': tutorial_1/newt-dev.md
    - 'Directory Layout': tutorial_1/layout.md
    - 'Building Blink': tutorial_1/blink.md
    - 'Building Sim': tutorial_1/sim.md
     
theme: mkdocs 

